name: PHPUnit Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install and update Composer packages
        run: |
          composer run-script install-dependencies
          composer run-script update-dependencies

      - name: Create environment file
        run: |
          touch .env
          printf "${{ secrets.PRIVATE_ENV }}" > .env

      - name: Run test suite
        run: composer run-script tests
